// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqaYPAgBAPjNE9raIONaDVCyN_6qazpzI',
    appId: '1:909132068681:web:1f4541445d85c47c068c98',
    messagingSenderId: '909132068681',
    projectId: 'apptransito-443a8',
    authDomain: 'apptransito-443a8.firebaseapp.com',
    storageBucket: 'apptransito-443a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZ8I-vpjcE9zgS66GyLg_bqems4ZJI20',
    appId: '1:909132068681:android:afa794fc75e29dd8068c98',
    messagingSenderId: '909132068681',
    projectId: 'apptransito-443a8',
    storageBucket: 'apptransito-443a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHkJRcLDA6NC39hDrE2gs5nCJ9QCyAIA',
    appId: '1:909132068681:ios:33606586cf6196f9068c98',
    messagingSenderId: '909132068681',
    projectId: 'apptransito-443a8',
    storageBucket: 'apptransito-443a8.appspot.com',
    iosBundleId: 'com.example.appTransito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHkJRcLDA6NC39hDrE2gs5nCJ9QCyAIA',
    appId: '1:909132068681:ios:85935ad27eda77bc068c98',
    messagingSenderId: '909132068681',
    projectId: 'apptransito-443a8',
    storageBucket: 'apptransito-443a8.appspot.com',
    iosBundleId: 'com.example.appTransito.RunnerTests',
  );
}
